from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    question: str = Field(
        min_length=3,
        max_length=300,
        description="The question you want to ask the Gemini model",
        examples=["What is artificial intelligence?"],
    )


class AskResponse(BaseModel):
    answer: str = Field(
        min_length=20,
        max_length=5000,
        description="The response generated by the Gemini model",
        examples=[
            "Artificial Intelligence (AI) is the simulation of human intelligence "
            "processes by machines..."
        ],
    )
